# Generated by Django 6.0.6 on 2026-07-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('website', 'Website Form'), ('google_ads', 'Google Ads'), ('linkedin', 'LinkedIn'), ('facebook_ads', 'Facebook Ads'), ('referral', 'Referrals'), ('consultant', 'Consultants'), ('networking', 'Networking Event'), ('email', 'Email Campaign'), ('manual', 'Manual Entry'), ('import', 'Excel/CSV Import')], default='manual', max_length=50)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Lost', 'Lost')], default='New', max_length=50)),
            ],
        ),
    ]
