# Generated by Django 6.0.6 on 2026-07-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook Ads'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual Entry')], default='manual', max_length=50),
        ),
    ]
