# Generated by Django 6.0.6 on 2026-07-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_pdf',
            field=models.FileField(blank=True, null=True, upload_to='lead_pdfs/'),
        ),
    ]
