# Generated by Django 6.0.6 on 2026-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_lead_current_requirements_lead_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('facebook', 'Facebook Ads'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('99acres', '99acres'), ('magicbricks', 'Magicbricks'), ('housing', 'Housing.com'), ('nobroker', 'NoBroker'), ('phone', 'Phone Call'), ('website', 'Website'), ('manual', 'Manual Entry')], default='manual', max_length=50),
        ),
    ]
