# Generated by Django 6.0.6 on 2026-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
