# Generated by Django 6.0.6 on 2026-08-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('', 'Select Reason'), ('Price Too High', 'Price Too High'), ('Customer Not Interested', 'Customer Not Interested'), ('Competitor Chosen', 'Competitor Chosen'), ('No Budget', 'No Budget'), ('No Response', 'No Response'), ('Product Not Suitable', 'Product Not Suitable'), ('Delayed Decision', 'Delayed Decision'), ('Duplicate Lead', 'Duplicate Lead'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
