# Generated by Django 6.0.6 on 2026-07-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=50)),
                ('company_size', models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('51+', '51+ Employees')], default='1-10', max_length=20)),
                ('requirement', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('timeline', models.CharField(choices=[('immediate', 'Immediate'), ('1-3_months', '1-3 Months'), ('3+', '3+ Months')], default='immediate', max_length=20)),
                ('decision_maker', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Qualified', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
