# Generated by Django 6.0.6 on 2026-07-09 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('business_challenges', models.TextField()),
                ('existing_process', models.TextField()),
                ('pain_points', models.TextField()),
                ('expected_outcomes', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('decision_maker', models.CharField(max_length=200)),
                ('timeline', models.CharField(max_length=100)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='InitialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('contact_method', models.CharField(choices=[('phone', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('video_call', 'Video Call'), ('office_visit', 'Office Visit')], max_length=20)),
                ('contact_person', models.CharField(max_length=100)),
                ('discussion_summary', models.TextField()),
                ('customer_response', models.TextField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('follow_up', 'Follow-up'), ('not_interested', 'Not Interested')], default='follow_up', max_length=20)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
