# Generated by Django 6.0.6 on 2026-07-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('functional_requirements', models.TextField(verbose_name='Functional Requirements (काय हवे आहे?)')),
                ('technical_requirements', models.TextField(verbose_name='Technical Requirements (तांत्रिक गरजा)')),
                ('proposed_solution', models.TextField(verbose_name='Proposed Solution (आपण काय देणार आहोत?)')),
                ('estimated_timeline', models.CharField(max_length=100, verbose_name='अपेक्षित कालावधी (उदा. २ महिने)')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('potential_risks', models.TextField(blank=True, null=True, verbose_name='Potential Risks')),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='leads.lead')),
            ],
        ),
    ]
